/* lib/tg-prices.ts — AUTO-GENERATED by scripts/fetch-mistore-prices.py
 * Источники: @mistore095, @istoregroznyy.
 * MAX-of-colors внутри модели/памяти; MAX между каналами; +1000₽ markup. */

export const TG_PRICES: Record<string, number> = {
  "airpods-max2": 45400,
  "airpods-pro3": 19800,
  "airpods4": 13000,
  "airpods4-anc": 17500,
  "apple-watch-ultra-2-49mm-korpus-iz-titana-remesok-ocean-sinego-cveta": 54500,
  "casy-apple-watch-series-11-42-mm-aluminij-cveta-rozovoe-zoloto-remesok-sport-band-cveta-svetlye-rumana": 31500,
  "casy-apple-watch-ultra-3-49-mm-titan-svetlogo-cveta-remesok-trail-cveta-sinijarko-sinij-2025": 63000,
  "ip13-128-2sim": 47000,
  "ip13-256-2sim": 51000,
  "ip15-128-sim": 54000,
  "ip15-256-sim": 62000,
  "ip16-128-sim": 61500,
  "ip17-256-esim": 74900,
  "ip17-256-sim": 74900,
  "ip17pro-1tb-esim": 132900,
  "ip17pro-1tb-sim": 132900,
  "ip17pro-512-esim": 117500,
  "ip17pro-512-sim": 117500,
  "ip17promax-1tb-esim": 143900,
  "ip17promax-1tb-sim": 143900,
  "ip17promax-256-esim": 109500,
  "ip17promax-256-sim": 109500,
  "tg-ip17e-256": 56000,
};
