/* lib/tg-prices.ts — AUTO-GENERATED by scripts/fetch-mistore-prices.py
 * Источники: @mistore095, @istoregroznyy.
 * MAX-of-colors внутри модели/памяти; MAX между каналами; +1000₽ markup. */

export const TG_PRICES: Record<string, number> = {
  "airpods-max2": 46000,
  "airpods-pro3": 19800,
  "airpods4": 12800,
  "airpods4-anc": 17500,
  "apple-watch-ultra-2-49mm-korpus-iz-titana-remesok-ocean-sinego-cveta": 54500,
  "casy-apple-watch-ultra-3-49-mm-titan-svetlogo-cveta-remesok-trail-cveta-sinijarko-sinij-2025": 63000,
  "ip13-128-2sim": 47000,
  "ip13-256-2sim": 51000,
  "ip15-128-sim": 54500,
  "ip15-256-sim": 62000,
  "ip16-128-sim": 62000,
  "ip16-512-sim": 58000,
  "ip17-256-esim": 72500,
  "ip17-256-sim": 72500,
  "ip17air-256-esim": 75000,
  "ip17pro-1tb-esim": 133500,
  "ip17pro-1tb-sim": 133500,
  "ip17pro-256-esim": 100500,
  "ip17pro-256-sim": 100500,
  "ip17pro-512-esim": 122000,
  "ip17pro-512-sim": 122000,
  "ip17promax-1tb-esim": 145900,
  "ip17promax-1tb-sim": 145900,
  "ip17promax-256-esim": 110000,
  "ip17promax-256-sim": 110000,
  "ip17promax-512-esim": 127900,
  "ip17promax-512-sim": 127900,
  "tg-ip17e-256": 56000,
};
