/* lib/tg-prices.ts — AUTO-GENERATED by scripts/fetch-mistore-prices.py
 * Источники: @mistore095, @istoregroznyy.
 * MAX-of-colors внутри модели/памяти; MAX между каналами; +1000₽ markup. */

export const TG_PRICES: Record<string, number> = {
};
