#!/usr/bin/env python3
"""
scripts/dedupe-biggeek.py

Берёт BIGGEEK_PRODUCTS из lib/biggeek-products.ts (сырой выгруз — 669 SKU),
группирует по (категория, модель+цвет), оставляет самый дешёвый вариант
каждой группы и переписывает файл компактно (~250–300 товаров).

Также:
  • декодирует HTML-entities в name (&quot; → ")
  • убирает технические скобки с GB/Core/M5 — оставляем только цвет/год
  • убирает MDxxx-SKU-коды
"""
import re
import html
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IN = ROOT / "lib" / "biggeek-products.ts"
OUT = ROOT / "lib" / "biggeek-products.ts"

content = IN.read_text()
rows = re.findall(
    r'\{ id:"([^"]+)", name:"([^"]+)", slug:"([^"]+)", category:"([^"]+)", '
    r'brand:"([^"]+)", price:(\d+), emoji:"([^"]+)", img:"([^"]+)"',
    content,
)
print(f"parsed: {len(rows)}")


def clean_name(name: str) -> str:
    s = html.unescape(name)
    # Убираем скобки со спеками (GB/TB/Core/M5/SSD/Wi-Fi)
    s = re.sub(r"\s*\([^)]*(?:GB|ГБ|ТБ|TB|Core|M\d|SSD|Wi-Fi)[^)]*\)", "", s, flags=re.I)
    # MDxxx-коды
    s = re.sub(r"\s+\b[A-Z]{2,5}\d{2,4}[A-Z]{0,3}\b", "", s)
    # «кастомный» — служебное слово
    s = re.sub(r"\s+кастомный\b", "", s, flags=re.I)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def model_color_key(clean: str, category: str) -> tuple:
    # Ключ группировки: имя БЕЗ цветовой скобки → один товар на модель+цвет.
    # Цвет уже в имени, поэтому ключ = имя как есть (без HTML), lower-case.
    return (category, clean.lower())


groups: dict = {}
for r in rows:
    id_, name, slug, category, brand, price, emoji, img = r
    price = int(price)
    clean = clean_name(name)
    k = model_color_key(clean, category)
    rec = dict(
        id=id_, name=clean, slug=slug, category=category, brand=brand,
        price=price, emoji=emoji, img=img,
    )
    if k not in groups or price < groups[k]["price"]:
        groups[k] = rec

products = list(groups.values())
print(f"after dedup: {len(products)}")

from collections import Counter
for cat, n in Counter(p["category"] for p in products).most_common():
    print(f"  {cat}: {n}")

# Сортируем: категория, затем цена
products.sort(key=lambda p: (p["category"], p["price"]))

lines = [
    "/* AUTO-GENERATED by scripts/import-biggeek-products.py + dedupe-biggeek.py.",
    "   Цены и изображения с biggeek.ru. Не править вручную — перезапускать скрипты. */",
    "",
    'import type { Product } from "./data";',
    "",
    "export const BIGGEEK_PRODUCTS: Product[] = [",
]
for p in products:
    name_esc = p["name"].replace("\\", "\\\\").replace('"', '\\"')
    lines.append(
        f'  {{ id:"{p["id"]}", name:"{name_esc}", slug:"{p["slug"]}",'
        f' category:"{p["category"]}", brand:"{p["brand"]}", price:{p["price"]},'
        f' emoji:"{p["emoji"]}", img:"{p["img"]}", inStock:true, rating:5,'
        f' reviewCount:0, description:"", specs:[] }},'
    )
lines.append("];")
OUT.write_text("\n".join(lines))
print(f"📝 wrote: {OUT}")
